# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://yrc00.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome to Yerim's Portfolio
# Description of the Site
description: All about Yerim Choi
# URL of Image of the Site
site-image: ./assets/images/avatar.png
# Keywords of the Site
site-keywords: AI, Developer, Protfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://plus.unsplash.com/premium_photo-1678052582163-c7b25ccde9e6?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: cyelim0621@gmail.com
facebook_username: 
twitter_username: 
instagram_username: yerim703
linkedin_username: 예림-최-4623882b5
github_username: yrc00
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: GTM-NRJR58NT

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Yerim Choi
# URL for the Image of the Author
author-image: ./assets/images/avatar.png
# 60 Words About the Author
author-about: Dankook University, Software Engineering, BITL, Artificial Intelligence, Machine Learning, Deep Learning, South Korea

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/yrc00

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
